<?php

namespace App\Http\Controllers;

use App\Repositories\ApkReleaseRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

/**
 * Версия приложения и раздача APK (Фаза 13, задача 13.1).
 *
 * Эндпоинт — точка правды для самообновления Android-клиента: приложение
 * сравнивает свой `versionCode` (нативный, см. `@capacitor/app`) с ответом и
 * предлагает «скачать и установить».
 *
 * До Фазы 13 контроллер брал `glob()[0]` (порядок файловой системы), а скачивание
 * сортировало файлы по `filemtime` — «версия» и «файл» могли разойтись, а
 * `versionCode` не отдавался вовсе. Теперь всё читается из манифеста релизов
 * (`App\Repositories\ApkReleaseRepository`); APK, лежащие прямо в
 * `storage/app/public/*.apk`, поддерживаются как легаси-путь.
 */
class AppVersionController extends Controller
{
    public function __construct(private readonly ApkReleaseRepository $releases)
    {
    }

    /** GET /api/app-version (исторический путь — /api/app-quasar-android-version). */
    public function checkQuasarAndroidVersion()
    {
        $release = $this->releases->latest();

        if ($release === null) {
            return $this->legacyVersionResponse();
        }

        return response()->json($this->versionPayload($release));
    }

    /** GET /api/download-apk[?versionCode=N] — файл релиза (или самый свежий). */
    public function downloadapk(Request $request)
    {
        try {
            $requested = $request->query('versionCode');
            $release = null;

            if ($requested !== null && $requested !== '') {
                $release = $this->releases->findByVersionCode((int) $requested);

                if ($release === null) {
                    return response()->json(['error' => "Релиз versionCode={$requested} не найден"], 404);
                }
            } else {
                $release = $this->releases->latest();
            }

            if ($release !== null) {
                $path = $this->releases->filePath($release);

                if ($path === null) {
                    return response()->json(['error' => 'Файл релиза не найден'], 404);
                }

                return $this->apkResponse($path, $release);
            }

            // Легаси: APK лежат прямо в storage/app/public (до появления манифеста).
            $legacyPath = $this->releases->legacyLatest();

            if ($legacyPath === null) {
                return response()->json(['error' => 'File not found'], 404);
            }

            return $this->apkResponse($legacyPath, null);
        } catch (\Exception $e) {
            \Log::error('Error downloading APK: '.$e->getMessage());

            return response()->json(['error' => 'Internal Server Error'], 500);
        }
    }


    /**
     * Манифест HCP — легаси Cordova-клиента соседнего репозитория
     * (`ledger-craft-quasar-spa`). Capacitor-клиент его не использует, маршрут
     * оставлен, чтобы ничего не ломать (решение D6, Фаза 13).
     */
    public function getChcpManifest(Request $request)
    {
        $manifest = [
            'autogenerated' => true,
            'content_url' => 'https://dev.medovf2h.beget.tech/hcp',
            'release' => '0.0.3',
            'update' => 'start',
        ];

        return response()->json($manifest);
    }

    /**
     * Ответ по манифесту: новый контракт + поля, которые контроллер отдавал до
     * Фазы 13 (`version`, `apk_name`) — чтобы уже собранные сборки не сломались.
     *
     * @param array<string, mixed> $release
     * @return array<string, mixed>
     */
    private function versionPayload(array $release): array
    {
        $versionCode = (int) $release['versionCode'];
        $versionName = (string) ($release['versionName'] ?? (string) $versionCode);

        return [
            'versionCode' => $versionCode,
            'versionName' => $versionName,
            'apkUrl' => url('/api/download-apk?versionCode='.$versionCode),
            'sha256' => (string) ($release['sha256'] ?? ''),
            'sizeBytes' => (int) ($release['sizeBytes'] ?? 0),
            'mandatory' => (bool) ($release['mandatory'] ?? false),
            'minSupportedVersionCode' => (int) ($release['minSupportedVersionCode'] ?? 0),
            'notes' => (string) ($release['notes'] ?? ''),
            'releasedAt' => $release['releasedAt'] ?? null,
            'signed' => (bool) ($release['signed'] ?? false),
            // Совместимость со старым ответом.
            'version' => $versionName,
            'apk_name' => (string) ($release['fileName'] ?? ''),
        ];
    }

    /**
     * Легаси-ответ, пока манифеста нет: версию достаём из имени файла, а
     * `versionCode` неизвестен (`null`) — клиент в этом случае сравнивает
     * `versionName` построчно (`src/utils/appUpdateView.js`).
     */
    private function legacyVersionResponse()
    {
        $latest = $this->releases->legacyLatest();

        if ($latest === null) {
            return response()->json(['error' => 'дистрибутив не найден'], 404);
        }

        $fileName = basename($latest);
        preg_match('/([\d.]+)(?:-[\w]+)?\.apk/', $fileName, $matches);
        $versionName = $matches[1] ?? null;

        return response()->json([
            'versionCode' => null,
            'versionName' => $versionName,
            'apkUrl' => url('/api/download-apk'),
            'sha256' => (string) hash_file('sha256', $latest),
            'sizeBytes' => (int) File::size($latest),
            'mandatory' => false,
            'minSupportedVersionCode' => 0,
            'notes' => '',
            'releasedAt' => date(DATE_ATOM, (int) filemtime($latest)),
            'signed' => null,
            'legacy' => true,
            'version' => $versionName,
            'apk_name' => $fileName,
        ]);
    }

    /**
     * Файл APK + метаданные в заголовках: клиент перед установкой сверяет sha256
     * (`X-Apk-Sha256`) и понимает, какую версию он скачал.
     *
     * @param array<string, mixed>|null $release
     */
    private function apkResponse(string $path, ?array $release): BinaryFileResponse
    {
        $fileName = basename($path);

        $response = response()->download($path, $fileName, [
            'Content-Type' => 'application/vnd.android.package-archive',
            'Content-Disposition' => 'attachment; filename="'.$fileName.'"',
        ]);

        if ($release !== null) {
            $response->headers->set('X-Apk-Version-Code', (string) (int) $release['versionCode']);
            $response->headers->set('X-Apk-Version-Name', (string) ($release['versionName'] ?? ''));
            $response->headers->set('X-Apk-Sha256', (string) ($release['sha256'] ?? ''));
        }

        return $response;
    }
}
